sonar.projectKey=secure-delivery-platform
sonar.projectName=Secure Delivery Platform
sonar.projectVersion=1.0

sonar.host.url=http://13.233.201.242:9000

sonar.sources=frontend/src,backend

sonar.exclusions=**/node_modules/**,**/venv/**,**/__pycache__/**,**/build/**

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.python.version=3.11